version: 0.0
Resources:
  - Kubernetes:
      Type: AWS::EKS::Deployment
      Properties:
        ClusterName: brain-tasks-cluster
        Namespace: default
        ManifestFiles:
          - k8s/deployment.yaml
          - k8s/service.yaml
